# Generated by Django 5.1.5 on 2025-01-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='content',
        ),
    ]
